# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
solc = "0.8.30"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = true

[fuzz]
runs = 4096

[invariant]
runs = 256

[fmt]
line_length = 120
tab_width = 4
sort_imports = true
wrap_comments = true
bracket_spacing = true
override_spacing = true
contract_new_lines = false
single_line_statement_blocks = "multi"
number_underscore = "thousands"
hex_underscore = "bytes"
