# Foundry Configuration for Security Tools PoC

[profile.default]
# Source directory
src = "src"
# Output directory
out = "out"
# Libraries directory
libs = ["lib"]
# Cache directory
cache_path = "cache"
# Artifacts directory
broadcast = "broadcast"

# Solidity compiler settings
solc_version = "0.8.19"
auto_detect_solc = true
optimizer = true
optimizer_runs = 200
via_ir = false
bytecode_hash = "none"
cbor_metadata = false
revert_strings = "default"

# EVM version
evm_version = "london"

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@forge-std/=lib/forge-std/src/",
    "ds-test/=lib/ds-test/src/"
]

# Fuzzing configuration
[profile.default.fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

# Invariant testing configuration
[profile.default.invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = []

# CI Profile (more thorough testing)
[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 20 }

# Lite Profile (faster testing)
[profile.lite]
fuzz = { runs = 100 }
invariant = { runs = 32, depth = 10 }

# RPC endpoints
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"

# Etherscan API keys
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
goerli = { key = "${ETHERSCAN_API_KEY}" }
sepolia = { key = "${ETHERSCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }

# Formatting
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"
single_line_statement_blocks = "preserve"